name: Build Data Artifact

on:
  workflow_dispatch:

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Create venv and install deps
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r scripts/requirements.txt
      shell: bash

    - name: Fetch datasets
      run: |
        source venv/bin/activate
        IFS=$' ' read -r -a DATASETS <<< "${{ vars.DATASETS }}"
        for DATASET in "${DATASETS[@]}"; do
          python scripts/get_neurons.py --root "$DATASET"
        done
      env:
        NEUPRINT_TOKEN: ${{ secrets.NEUPRINT_TOKEN }}
      shell: bash

    - name: Upload data artifact
      uses: actions/upload-artifact@v7
      with:
        name: data
        path: data
